### ISSUE TITLE
Dashboard is empty.

### ISSUE THREAD

**Issue by AndyDufresne422** [lllllllillllllillll/DweebUI#97]
I'm not sure what I did but my dashboard is empty after migrating my server to a new VPS.

I installed all containers from scratch but rsync'd all the persistent data from server 1 to server 2. 

### On server 1 
I could see all containers on the dashboard as well as the networks and volumes and images. 

### On server 2 
I can see the networks, volumes and images, but nothing shows up on the dashboard. Any help would be appreciated.

Things I've tried:
- Removing dweebui and image and volume and re-pulling/re-installing
- restart the server
- bind mount the config folder to a local folder
- bind mount to a docker volume

Any help appreciated!

<img width="1385" alt="Screenshot 2024-07-27 at 4 15 01 PM" src="https://github.com/user-attachments/assets/87e4812c-5a90-4c34-8aad-5b072f6ed412">

**Comment by lllllllillllllillll** [comment]
Aw heck. Uh. 🤔

- The connection to the Docker instance must be fine if you can see the images, volumes, and networks. 
- You're probably connecting to it from the same browser and method as the previous server. 
- You probably installed it using the same setup as the other server.

Are you able to view the logs? I believe that version displays "SSE Event" in console before the cards appear.
Does it show your role as admin?

The dashboard uses htmx, the htmx server-side events extension, and displays images that are being stored on github. 
You're browser console may be displaying errors about one of those being blocked or not loading properly. 

Try clearing browser cache or using a private window. Possibly a different browser.
Don't use bind mounts. 
Try with v0.60, v0.70-dev, or latest.

**Comment by AndyDufresne422** [comment]
@lllllllillllllillll thanks for checking in. (and really nice work on dweebui, btw!)

I viewed the docker logs and syslogs in the dweebui panel. Both look normal and show no errors.
I am listed as admin in the dweebui users panel.

### I did the following with the following results:

|What I did...|How it went...|
|-----------|--------------|
|Checked the log:|Looked normal: ```DB Connection: ✔️ Synced Models: ✔️ Listening on http://localhost:8000```|
|Reinstalled using tag "latest"| No change|
|Reinstalled using tag "v0.60"|Got a console error about a form attribute on registry, but was not there after i refreshed the page.|
|Cleared browser cache|No change|
|Cleared cloudflare cache|No change|
|Ate dinner|Didn't make a difference either... though *I* felt better.|


### Update... (see video below)
So oddly, while I was writing this, it loaded... but it has about 6 duplicates of every container. Instead of the 30 that are running it looks like nearly 200 cards... And about 20 errors in the console. My guess is that this is causing the issue as it's trying to load too much data or stuck in a loop...

```
Uncaught SyntaxError: Unexpected token '.'
    at At (htmx.min.js:1:22924)
    at htmx.min.js:1:23086
    at oe (htmx.min.js:1:4604)
    at Nt (htmx.min.js:1:23057)
    at htmx.min.js:1:10309
    at htmx.min.js:1:44741
    at oe (htmx.min.js:1:4604)
    at s (htmx.min.js:1:44716)
```

### The endless scrolling of container cards...
https://github.com/user-attachments/assets/50a8cd1b-6631-4b86-9bef-ca790406a9fd

**Comment by lllllllillllllillll** [comment]
Thanks for all the information. It helps a lot.
`Uncaught TypeError: Cannot read properties of undefined (reading 'jitsichart')`
You have a container named jitsi? or are there some characters missing? I think I needed to remove "-" characters at some point. Other characters in the name might be causing issues.

I'm thinking I need to add a toggle in preferences to hide your name from the dashboard as well.

My next release has a lot of huge improvements, which should avoid this, but it's far from functional at the moment. I'll see how much I can get done tomorrow.

**Comment by AndyDufresne422** [comment]
@lllllllillllllillll Thanks again for the follow up.

I do have a container named Jitsi, (it's a self hosted zoom alternative for a small volunteer group I'm a part of.) 

I'm sure it's my setup that is somehow causing these issues, since it worked perfectly on the first server.

I'll wait patiently for the next release and try again.

If you have any further questions or additional suggestions let me know, I'm willing to help troubleshoot, but also appreciate the help you have already provided.

Cheers!

**Comment by AndyDufresne422** [comment]
In case it's helpful, here's the entire console log of errors after about 10-15 minutes.

[dash.sub.domain.tld-1722184662481.log](https://github.com/user-attachments/files/16404540/dash.sub.domain.tld-1722184662481.log)

**Comment by lllllllillllllillll** [comment]
@AndyDufresne422  

I just pushed out a new docker image that shouldn't have this issue:  v0.7X-dev (Extra Broken).
If you want to try it out: 

- Stop/Remove DweebUI container
- Remove any existing DweebUI volumes
- Remove any existing DweebUI images
- Pull the latest v0.7X-dev with:
 `docker run -d --name=DweebUI -p 8000:8000 -v dweebui:/app/database -v /var/run/docker.sock:/var/run/docker.sock lllllllillllllillll/dweebui:v0.7X-dev`
 
 *Make sure its all on one line
